pipeline {

    agent {
        docker {
            image 'python:2.7.16-slim'
            args '--user root'
        }
    }



    stages{
        stage('build'){
            when {
                changeset "**/vote/**"
            }
            steps {
               echo 'Compiling vote app'
               dir('vote'){
                sh 'pip install -r requirements.txt'
                }
            }

        }
        stage('test'){
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Running Unit Tests on Vote app'
                dir('vote'){
                 sh 'nosetests -v'
                 }
            }

        }

    }
    post {
        always {
           echo 'Pipeline for vote is complete..'
        }
        failure {
            slackSend (message: "Build failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
            slackSend (message: "Build successful - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}