pipeline {

    agent any

    tools {
        maven  'Maven 3.6.1'
    }

    stages{
        stage('build'){
            when {
                changeset "**/worker/**"
            }
            steps {
               echo 'Compiling worker app'
               dir('worker'){
                sh 'mvn compile'
                }
            }

        }
        stage('test'){
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Tests on Worker app'
                dir('worker'){
                 sh 'mvn clean test'
                 }
            }

        }
        stage('package'){
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                 echo 'Packaging Worker app'
                  dir('worker'){
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                    }
            }

        }
    }
    post {
        always {
           echo 'Build pipeline for worker is complete..'
        }
        failure {
            slackSend (message: "Build failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
            slackSend (message: "Build successful - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}