pipeline {

    agent any

    tools {
        maven  'Maven 3.6.1'
    }

    stages{
        stage('build'){
            steps {
               echo 'Compiling worker app'
               dir('worker'){
                sh 'mvn compile'
                }
            }

        }
        stage('test'){
            steps {
                echo 'Running Unit Tests on Worker app'
                dir('worker'){
                 sh 'mvn clean test'
                 }
            }

        }
        stage('package'){
            steps {
                 echo 'Packaging Worker app'
                  dir('worker'){
                    sh 'mvn package -DskipTests'
                    }
            }

        }
    }
    post {
        always {
           archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
           echo 'Build pipeline for worker is complete..'
        }
    }
}